// Database Configuration
// Generated by SETUP-SIMPLE.ps1
// Date: 10/05/2025 22:36:52

module.exports = {
    host: 'localhost',
    user: 'student_lab_user',
    password: 'StudentLab2024!Secure',
    database: 'student_lab_system',
    charset: 'utf8mb4',
    connectionLimit: 10,
    acquireTimeout: 60000,
    timeout: 60000,
    reconnect: true,
    multipleStatements: true,
    dateStrings: true,
    supportBigNumbers: true,
    bigNumberStrings: true
};
